SELECT 
    A.PRODUCT_ID,
    A.PRODUCT_NAME,
    SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS A
        JOIN
    FOOD_ORDER AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE
    PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC , PRODUCT_ID;


-- 다른 답안
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC