SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.TOTAL_SALES) AS TOTAL_SALES
FROM
    AUTHOR AS A
        JOIN
    (SELECT 
        A.AUTHOR_ID, A.CATEGORY, (A.PRICE * C.SALES) AS TOTAL_SALES
    FROM
        BOOK AS A
    JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
    WHERE
        SALES_DATE LIKE '2022-01%') AS B ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY B.AUTHOR_ID , A.CATEGORY
ORDER BY 1 , 3 DESC;