SELECT 
    A.CAR_ID,
    A.CAR_TYPE,
    FLOOR((A.DAILY_FEE * (1 - C.DISCOUNT_RATE/100)) * 30) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS A
        JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
        JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE
    A.CAR_TYPE IN ('세단' , 'suv')
        AND C.DURATION_TYPE = '30일 이상'
GROUP BY A.CAR_ID
HAVING (MAX(END_DATE) < '2022-11-01'
    OR MAX(END_DATE) IS NULL)
    AND FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC , CAR_TYPE , CAR_ID DESC;